made theme script not bad

diff --git a/theme/.local/bin/theme b/theme/.local/bin/theme
--- a/theme/.local/bin/theme
+++ b/theme/.local/bin/theme
@@ -1,49 +1,44 @@
 #!/bin/sh
 
-CONFIG="$XDG_CONFIG_HOME/theme/config"
+EXTENSION="env"
+THEME_SUBDIR="themes"
+SCRIPT_SUBDIR="scripts"
+CONFIG_DIR="$HOME/.config/theme"
+[ -n "$XDG_CONFIG_HOME" ] && CONFIG_DIR="$XDG_CONFIG_HOME/theme"
+THEME_DIR="$CONFIG_DIR/$THEME_SUBDIR"
+SCRIPT_DIR="$CONFIG_DIR/$SCRIPT_SUBDIR"
 
 help () {
     echo "theme: Changes config files to match a theme"
-    echo "  Usage: theme <theme> <scheme>"
+    echo "  Usage: theme <theme>"
     echo "  Options:"
     echo "    -h, --help                display this message and exit"
     echo "    -v, --version             display program version"
-    echo "    -c, --config <path>       specify alternate config location"
-    echo "  Config Format:"
-    echo "    Each line in the config is an action taken when changing the theme"
-    echo "    There are currently three different action types"
-    echo '      cmd <command>           runs the specified command. $theme and $scheme'
-    echo "                              are available to use within this"
-    echo "      link <source> <dest>    will create a symlink from <source>/<theme>-<scheme>"
-    echo "                              to <dest>"
-    echo "      file <source> <dest>    will copy the file from <source> to <dest>, replacing"
-    echo '                              all instances of $theme and $scheme within it'
-    echo "    # can specify comments"
+    echo "    -l, --list                list all available themes"
+    echo "    -c, --config <path>       specify alternate config directory location"
+    echo "                              (default: $CONFIG_DIR)"
+    echo "  Configuration:"
+    echo "    Each file in <config>/$THEME_SUBDIR is named <theme>.$EXTENSION"
+    echo "      These files are interpreted as scripts and their variables are exported for use"
+    echo "      For a simple use, each line is <variable>=<value>"
+    echo "    Each file in <config>/$SCRIPT_SUBDIR is an executable"
+    echo "      The variables within the themes are given to the scripts"
+    echo "      Additionally, the variable 'theme' is given, set to <theme>"
 }
 
 version () {
-    echo "1.0"
+    echo "1.2"
 }
 
-check_config () {
-    [ ! -f "$CONFIG" ] && echo "Config file not found. Check path" && exit 1
+list () {
+    [ ! -d "$THEME_DIR" ] && return
+    for theme in "$THEME_DIR"/*; do
+        theme="$(basename "$theme")"
+        [ "${theme##*.}" = "$EXTENSION" ] && echo "${theme%.*}"
+    done
 }
 
-link () {
-    src="$(sh -c "echo \"$1\"")/$theme-$scheme"
-    dst="$(sh -c "echo \"$2\"")"
-    [ ! -f "$src" ] && [ ! -d "$src"] && echo "file does not exist: $src" && exit 1
-    ln -sf "$src" "$dst"
-}
-
-file () {
-    src="$(sh -c "echo \"$1\"")"
-    dst="$(sh -c "echo \"$2\"")"
-    [ ! -f "$src" ] && echo "file does not exist: $src" && exit 1
-    theme=$theme scheme=$scheme envsubst < "$src" > "$dst"
-}
-
-opts=$(! getopt -l "help,version,config:" -o "hvc:" -- $@ 2> /dev/null) && help && exit 1
+opts=$(! getopt -l "help,version,list,config:" -o "hvlc:" -- $@ 2> /dev/null) && help >&2 && exit 1
 eval set -- "$opts"
 
 while [ "$#" -gt 0 ]; do
@@ -58,7 +53,13 @@ while [ "$#" -gt 0 ]; do
             ;;
         -c|--config)
             shift
-            CONFIG="$1"
+            CONFIG_DIR="$1"
+            THEME_DIR="$CONFIG_DIR/$THEME_SUBDIR"
+            SCRIPT_DIR="$CONFIG_DIR/$SCRIPT_SUBDIR"
+            exit 0
+            ;;
+        -l|--list)
+            list
             exit 0
             ;;
         --)
@@ -68,33 +69,22 @@ while [ "$#" -gt 0 ]; do
     esac
     shift
 done
-check_config
 
-[ "$#" -ne 2 ] && help && exit 1
+[ "$#" -ne 1 ] && help >&2 && exit 1
+
+# check that theme is valid
+[ ! -f "$THEME_DIR/$1.$EXTENSION" ] && echo "Theme not found" >&2 && exit 1
+
+# source file
+set -a
+source "$THEME_DIR/$1.$EXTENSION"
 theme="$1"
-scheme="$2"
+set +a
 
-while read line; do
-    cmd="${line%% *}"
-    opt="${line#* }"
-
-    case "$cmd" in
-        "#"*|"")
-            continue
-            ;;
-        cmd)
-            theme=$theme scheme=$scheme sh -c "$opt"
-            [ "$?" -ne 0 ] && echo "Error running $line" && exit 1
-            ;;
-        link)
-            link $opt
-            ;;
-        file)
-            file $opt
-            ;;
-        *)
-            echo "Unknown command: $line" && exit 1
-            ;;
-    esac
-done < "$CONFIG"
+# run every script
+[ ! -d "$SCRIPT_DIR" ] && exit 0
+for script in "$SCRIPT_DIR"/*; do
+    script="$(basename "$script")"
+    "$SCRIPT_DIR/$script" > /dev/null 2>&1 || echo "Error executing $SCRIPT_DIR/$script" >&2
+done
 exit 0
